# Generated by Django 4.1.4 on 2023-01-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=50)),
                ('word', models.TextField(max_length=50)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
