# Generated by Django 4.1.4 on 2023-01-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_usersearchhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSearchHistory',
        ),
        migrations.AddField(
            model_name='dictionary',
            name='example_1',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='example_2',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='no_of_searches',
            field=models.IntegerField(default=0),
        ),
    ]
