# Generated by Django 4.1.4 on 2023-01-24 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_dictionary_diplayed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionary',
            old_name='diplayed',
            new_name='displayed',
        ),
    ]
